export const IMAGEN_CREATE_PROVIDER = 'IMAGEN_CREATE_PROVIDER';
export const IMAGEN_FIND_BY_ID_PROVIDER = 'IMAGEN_FIND_BY_ID_PROVIDER';
export const IMAGEN_DELETE_PROVIDER = 'IMAGEN_DELETE_PROVIDER';
export const IMAGEN_UPDATE_PROVIDER = 'IMAGEN_UPDATE_PROVIDER';

export const STOCK_CREATE_PROVIDER = 'STOCK_CREATE_PROVIDER';
export const STOCK_FIND_BY_ID_PROVIDER = 'STOCK_FIND_BY_ID_PROVIDER';
export const STOCK_DELETE_PROVIDER = 'STOCK_DELETE_PROVIDER';
export const STOCK_UPDATE_PROVIDER = 'STOCK_UPDATE_PROVIDER';
